name: Greeting on variable day

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Variable Test"
        run: echo "My Variable is ${{ vars.VAR-ACT }}"
